apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-did-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: maipol
  - name: scale-central-1a
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["eu-central-1a"]
    iam:
      withAddonPolicies:
        autoscaler: true
    labels:
      nodegroup-type: stateful-central1a
      instanceType: onDemand
    ssh:
      publicKeyName: maipol
  - name: scale-central-1b
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["eu-central-1b"]
    iam:
      withAddonPolicies:
        autoscaler: true
    labels:
      nodegroup-type: stateful-central1b
      instanceType: onDemand
    ssh:
      publicKeyName: maipol
  - name: scale-spot
    desiredCapacity: 1
    maxSize: 10
    instancesDistribution:
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["eu-central-1a","eu-central-1c"]  
    iam:
      withAddonPolicies:
        autoscaler: true
    labels:
      nodegroup-type: stateless-workload
      instanceType: spot
    ssh:
      publicKeyName: maipol
   